version: '3.8'

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - PHX_HOST=localhost
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
      #ports:
      #- "4000:4000"
    command: sleep infinity
